# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.cache/wt [current_project]
set_property parent.project_path D:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo d:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.srcs/sources_1/new/Sound_Detection.vhd
  D:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.srcs/sources_1/new/LightCTRL.vhd
  D:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.srcs/sources_1/new/temp.vhd
  D:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.srcs/sources_1/new/Motion_Detection.vhd
  D:/Lesson/TERM7/FPGA/Szamani/Project/project_4/project_4.srcs/sources_1/new/CMDCTRL.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CMDCTRL -part xc7z020clg484-1


write_checkpoint -force -noxdef CMDCTRL.dcp

catch { report_utilization -file CMDCTRL_utilization_synth.rpt -pb CMDCTRL_utilization_synth.pb }
